# Generated by Django 3.1.7 on 2022-04-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_title', models.CharField(blank=True, max_length=250)),
                ('a_tag', models.CharField(blank=True, max_length=250)),
                ('a_author', models.CharField(blank=True, max_length=100)),
                ('a_body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['a_id'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=150)),
                ('c_description', models.CharField(blank=True, max_length=250)),
                ('c_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['c_id'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(blank=True, max_length=250)),
                ('p_title_tag', models.CharField(blank=True, max_length=250)),
                ('p_author', models.CharField(blank=True, max_length=100)),
                ('p_body', models.TextField(blank=True)),
                ('p_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['p_id'],
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_category', models.CharField(max_length=100, null=True)),
                ('s_email', models.CharField(max_length=100, null=True)),
                ('s_message', models.TextField(blank=True, null=True)),
                ('s_status', models.CharField(default='0', max_length=10, null=True)),
                ('s_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['s_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemUsers',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_firstname', models.CharField(blank=True, max_length=100)),
                ('s_lastname', models.CharField(blank=True, max_length=100)),
                ('s_phone', models.CharField(blank=True, max_length=20)),
                ('s_email', models.CharField(blank=True, max_length=100)),
                ('s_passwd', models.CharField(blank=True, max_length=100)),
                ('s_country', models.CharField(blank=True, max_length=100)),
                ('s_role', models.CharField(blank=True, max_length=50)),
                ('s_status', models.CharField(blank=True, default='inactive', max_length=50)),
                ('c_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['s_id'],
            },
        ),
    ]
